defmodule Tunez.Repo.Migrations.AddGinIndexForArtistNameSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :previous_names, {:array, :text}, default: []
    end

    create index(:artists, ["name gin_trgm_ops"], name: "artist_name_gin_index", using: "GIN")
  end

  def down do
    drop_if_exists index(:artists, ["name gin_trgm_ops"], name: "artist_name_gin_index")

    alter table(:artists) do
      remove :previous_names
    end
  end
end
